name: com_joaojsrbr_reader

description: Read manga, manhwa and manhua.

publish_to: "none"

version: 1.1.10

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_core_platform_interface: ^4.5.0
  firebase_app_check: ^0.0.6+20
  firebase_core: ^1.21.0
  firebase_database: ^9.1.2
  firebase_auth: ^3.6.4
  dio_http_cache: ^0.3.0
  html: ^0.15.0
  google_sign_in: ^5.3.2
  flutter_signin_button: ^2.0.0
  awesome_notifications: any
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  provider: ^6.0.3
  mobx: ^2.0.7+2
  package_info_plus: ^1.4.0
  flutter_mobx: ^2.0.6+1
  path: ^1.8.1
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
  flutter_native_splash: ^2.2.7
  flutter_svg: ^1.1.0
  slugify: ^2.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  collection: ^1.16.0
  sqflite: ^2.0.2+1
  workmanager: ^0.5.0
  get: ^4.6.5
  flutter_cache_manager: ^3.3.0
  graphql_flutter: ^5.1.0
  sliver_tools: ^0.2.7
  loading_more_list: ^4.1.2
  custom_selectable_text: ^0.2.0
  dynamic_color: ^1.4.0
  # boxy: ^2.0.6+2
  # carousel_slider: ^4.1.1
  # select_button:
  #   path: lib/app/core/packages/commons/select_button
  # hidable: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  mobx_codegen: ^2.0.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo3.png"
  adaptive_icon_background: "#101014"

flutter_native_splash:
  image: "assets/images/logo.png"
  android: true
  color_dark: "#000000"
  color: "#000000"
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.svg
    - assets/images/logo3.png
    - assets/images/animated-bell.gif
  fonts:
    - family: iconsax
      fonts:
        - asset: assets/fonts/iconsax.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
