name: A.N.R

description: Read manga, manhwa, manhua, novels and webtoons.

publish_to: "none"

version: 1.1.22

environment:
  sdk: ">=2.17.1 <3.0.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  html: ^0.15.0
  firebase_core: ^1.17.1
  firebase_database: ^9.0.15
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.2
  flutter_signin_button: ^2.0.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  provider: ^6.0.3
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  path: ^1.8.1
  webview_flutter: ^3.0.4
  flutter_native_splash: ^2.2.2
  flutter_svg: ^1.1.0
  slugify: ^2.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  collection: ^1.16.0
  sqflite: ^2.0.2+1
  workmanager: ^0.5.0
  get: ^4.6.5
  flutter_cache_manager: ^3.3.0
  dynamic_color: ^1.4.0
  graphql_flutter: ^5.1.0
  sliver_tools: ^0.2.7
  flutter_inappwebview: ^5.4.3+7
  loading_more_list: 4.1.2
  # dart_ping: ^7.0.1
  scrollable_positioned_list: ^0.3.2
  fast_immutable_collections: ^7.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
